name: Create ZIP Archive

on:
  push:
    branches: [ main ]
    paths: [ 'files/**' ]
  workflow_dispatch:

jobs:
  create-zip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Create ZIP archive
      run: |
        cd files
        zip -r ../all_files.zip *
        
    - name: Upload ZIP file
      uses: actions/upload-artifact@v3
      with:
        name: all_files.zip
        path: all_files.zip
        
    - name: Commit and push ZIP
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add all_files.zip
        git commit -m "Update ZIP archive" || echo "No changes to commit"
        git push
