name: Generate files tree JSON and ZIP archives

on:
  push:
    branches:
      - main

jobs:
  generate-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate files tree JSON
        run: |
          node scripts/generate-tree.js

      - name: Create ZIP archives for each folder in files/
        run: |
          mkdir -p files/zips
          for dir in files/*/ ; do
            folder=$(basename "$dir")
            zip -r "files/zips/$folder.zip" "$dir"
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add files/tree.json files/zips/*.zip
          git diff --cached --quiet || git commit -m "Update files tree JSON and ZIPs"
          git push
