name: Zip each subfolder in files/

on:
  push:
    paths:
      - 'files/**'
  workflow_dispatch:

jobs:
  zip-each-folder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create zips folder
        run: mkdir -p zips

      - name: Zip each folder in files/
        run: |
          for dir in files/*/; do
            name=$(basename "$dir")
            zip -r "zips/${name}.zip" "$dir"
          done

      - name: Copy individual files in files/ root
        run: |
          for f in files/*; do
            if [ -f "$f" ]; then
              name=$(basename "$f" | cut -d. -f1)
              zip -j "zips/${name}.zip" "$f"
            fi
          done

      - name: Push zipped files to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git fetch
          git checkout main
          cp -r zips ./zips
          git add zips
          git commit -m "Update zipped folders"
          git push
